USE [master]
GO

/****** Object:  Database [sampledatabase]    Script Date: 22/03/2022 23:50:43 ******/
CREATE DATABASE [sampledatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'sampledatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.ALFREDOSQL\MSSQL\DATA\sampledatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'sampledatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.ALFREDOSQL\MSSQL\DATA\sampledatabase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [sampledatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [sampledatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [sampledatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [sampledatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [sampledatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [sampledatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [sampledatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [sampledatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [sampledatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [sampledatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [sampledatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [sampledatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [sampledatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [sampledatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [sampledatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [sampledatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [sampledatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [sampledatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [sampledatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [sampledatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [sampledatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [sampledatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [sampledatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [sampledatabase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [sampledatabase] SET  MULTI_USER 
GO

ALTER DATABASE [sampledatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [sampledatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [sampledatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [sampledatabase] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [sampledatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [sampledatabase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [sampledatabase] SET QUERY_STORE = OFF
GO

ALTER DATABASE [sampledatabase] SET  READ_WRITE 
GO

